sonar.projectKey=tasklist-backend-catherine
sonar.projectName=TaskList Backend
sonar.projectVersion=1.0

# Chemin des sources analysées
sonar.sources=src
sonar.exclusions=src/__tests__/**,dist/**,node_modules/**

# Chemin des tests
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

# Rapport de couverture (généré par vitest --coverage, reporter lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Rapport de tests au format JUnit (généré par vitest, reporter junit)
sonar.testExecutionReportPaths=reports/junit.xml

sonar.sourceEncoding=UTF-8